version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      LOG_CHANNEL: 'stderr'
    volumes:
      - .:/app
    expose:
      - 9000
    tty: true
    restart: always